# References:
#
# https://github.com/marketplace/actions/hugo-static-site-generator
# https://retrolog.io/blog/creating-a-hugo-theme-from-scratch/

baseURL = 'https://cpanel.github.io/elevate'
languageCode = 'en-us'
title = 'cPanel elevate documentation'
theme = "cptheme"

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    name = "Report an Issue"
    url = "https://docs.cpanel.net/knowledge-base/technical-support-services/how-to-open-a-technical-support-ticket/"
    weight = 1

  [[menu.main]]
    name = "Contribute"
    url = "https://github.com/cpanel/elevate"
    weight = 2

##
## left menu
##
  [[menu.left]]
    name = "Introduction"
    url = "/#introduction"
    weight = 1

  [[menu.left]]
    name = "Before Updating"
    url = "/#before-updating"
    weight = 2

  [[menu.left]]
    name = "Risks"
    url = "/#risks"
    weight = 3

  [[menu.left]]
    name = "Using the script"
    url = "/#using-the-script"
    weight = 4

  [[menu.left]]
    name = "SumUp of upgrade process"
    url = "/#SumUp-of-upgrade-process"
    weight = 5

  [[menu.left]]
    name = "Copyright"
    url = "/#copyright"
    weight = 6
